export const FETCH_ACTIVE_GAMES = 'FETCH_ACTIVE_GAMES';
export const FETCH_ACTIVE_GAMES_START = 'FETCH_ACTIVE_GAMES_START';
export const FETCH_ACTIVE_GAMES_SUCCESS = 'FETCH_ACTIVE_GAMES_SUCCESS';
export const FETCH_ACTIVE_GAMES_FAILED = 'FETCH_ACTIVE_GAMES_FAILED';

export const CREATE_NEW_GAME = 'CREATE_NEW_GAME';
export const CREATE_NEW_GAME_START = 'CREATE_NEW_GAME_START';
export const CREATE_NEW_GAME_SUCCESS = 'CREATE_NEW_GAME_SUCCESS';
export const CREATE_NEW_GAME_FAILED = 'CREATE_NEW_GAME_FAILED';




