export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_SET_TIMEOUT = 'AUTH_SET_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const CREATING_GAME = 'CREATING_GAME';
export const CREATE_GAME_START = 'CREATE_GAME_START';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILED = 'CREATE_GAME_FAILED';

export const FETCHING_GAMES = 'FETCHING_GAMES';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILED = 'FETCH_GAMES_FAILED';

export const FETCHING_SINGLE_GAME = 'FETCHING_SINGLE_GAME';
export const FETCH_SINGLE_GAME_SUCCESS = 'FETCH_SINGLE_GAME_SUCCESS';
export const FETCH_SINGLE_GAME_FAILED = 'FETCH_SINGLE_GAME_FAILED';