export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_SET_TIMEOUT = 'AUTH_SET_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const FETCH_ACTIVE_GAMES = 'FETCH_ACTIVE_GAMES';
export const FETCH_ACTIVE_GAMES_START = 'FETCH_ACTIVE_GAMES_START';
export const FETCH_ACTIVE_GAMES_SUCCESS = 'FETCH_ACTIVE_GAMES_SUCCESS';
export const FETCH_ACTIVE_GAMES_FAILED = 'FETCH_ACTIVE_GAMES_FAILED';

export const CREATE_NEW_GAME = 'CREATE_NEW_GAME';
export const CREATE_NEW_GAME_START = 'CREATE_NEW_GAME_START';
export const CREATE_NEW_GAME_SUCCESS = 'CREATE_NEW_GAME_SUCCESS';
export const CREATE_NEW_GAME_FAILED = 'CREATE_NEW_GAME_FAILED';




